--실습과제 4
SELECT NAME
FROM CUSTOMERS
ORDER BY NAME ASC;

SELECT ACCOUNT_ID, BALANCE
FROM ACCOUNTS
ORDER BY BALANCE DESC;

SELECT TRANSACTION_ID, AMOUNT
FROM TRANSACTIONS
ORDER BY AMOUNT ASC;

SELECT LOAN_ID, CUSTOMER_ID
FROM LOANS
ORDER BY AMOUNT DESC;