CREATE TABLE CUSTOMER_INFO(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50),
    PHONE NUMBER NOT NULL,
    ADDRESS VARCHAR2(100),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE ACCOUNT_INFO(
    ACCOUNT_ID NUMBER PRIMARY KEY,
    ACCOUNT_NUMBER NUMBER NOT NULL,
    BALANCE NUMBER DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE HOLDING(
    HOLDING_ID NUMBER PRIMARY KEY,
    QUANTITY NUMBER NOT NULL,
    AVARAGE_PRICE NUMBER,
    LAST_UPDATED DATE DEFAULT SYSDATE
);

CREATE TABLE SECURITIES_ORDERS(
    ORDER_ID NUMBER PRIMARY KEY,
    ORDERT_TYPE VARCHAR2(10),
    QUANTITY NUMBER,
    PRICE NUMBER,
    ORDER_STATUS VARCHAR2(10),
    ORDER_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE STOCK_INFO(
    STOCK_ID NUMBER PRIMARY KEY,
    SECTOR VARCHAR2(50),
    MARKET VARCHAR2(50)
);

CREATE TABLE COMPANY_INFO(
    COMPANY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    OPEN_DATE DATE,
    CEO VARCHAR2(50)
);

COMMIT;

ALTER TABLE ACCOUNT_INFO
ADD FK_CUSTOMER_ID NUMBER;

ALTER TABLE ACCOUNT_INFO
ADD CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY(FK_CUSTOMER_ID)
REFERENCES CUSTOMER_INFO(CUSTOMER_ID);

ALTER TABLE HOLDING
ADD FK_ACCOUNT_ID NUMBER;

ALTER TABLE HOLDING
ADD CONSTRAINT FK_HOLDING_ACCOUNT FOREIGN KEY(FK_ACCOUNT_ID) REFERENCES ACCOUNT_INFO
(ACCOUNT_ID);

ALTER TABLE HOLDING
ADD FK_STOCK_ID NUMBER;

ALTER TABLE HOLDING
ADD CONSTRAINT FK_HOLDING_STOCK FOREIGN KEY(FK_STOCK_ID)
REFERENCES STOCK_INFO(STOCK_ID);

ALTER TABLE HOLDING
ADD FK_CUSTOMER_ID NUMBER;

ALTER TABLE HOLDING
ADD CONSTRAINT FK_HOLDING_CUSTOMER FOREIGN KEY(FK_CUSTOMER_ID)
REFERENCES CUSTOMER_INFO(CUSTOMER_ID);

ALTER TABLE SECURITIES_ORDERS
ADD FK_STOCK_ID NUMBER;

ALTER TABLE SECURITIES_ORDERS
ADD CONSTRAINT FK_SECURITIES_ORDERS_STOCK FOREIGN KEY(FK_STOCK_ID)
REFERENCES STOCK_INFO(STOCK_ID);

ALTER TABLE SECURITIES_ORDERS
ADD FK_ACCOUNT_ID NUMBER;

ALTER TABLE SECURITIES_ORDERS
ADD CONSTRAINT FK_SECURITIES_ORDERS_ACCOUNT FOREIGN KEY(FK_ACCOUNT_ID)
REFERENCES ACCOUNT_INFO(ACCOUNT_ID);

ALTER TABLE SECURITIES_ORDERS
ADD FK_CUSTOMER_ID NUMBER;

ALTER TABLE SECURITIES_ORDERS
ADD CONSTRAINT FK_SECURITIES_ORDERS_CUSTOMER FOREIGN KEY(FK_CUSTOMER_ID)
REFERENCES CUSTOMER_INFO(CUSTOMER_ID);

ALTER TABLE STOCK_INFO
ADD FK_COMPANY_ID NUMBER;

ALTER TABLE STOCK_INFO
ADD CONSTRAINT FK_STOCK_COMPANY FOREIGN KEY(FK_COMPANY_ID)
REFERENCES COMPANY_INFO(COMPANY_ID);

COMMIT;

INSERT INTO CUSTOMER_INFO (CUSTOMER_ID, NAME, PHONE)
VALUES (1, 'KIMSEONGHYEON', 01012345678);

INSERT INTO COMPANY_INFO (COMPANY_ID, NAME, OPEN_DATE, CEO)
VALUES(1, '다우기술', DATE '1986-01-17', '김윤덕');

INSERT INTO STOCK_INFO (STOCK_ID, FK_COMPANY_ID, SECTOR, MARKET)
VALUES(1, 1, 'AI', '국내');

INSERT INTO ACCOUNT_INFO (ACCOUNT_ID, FK_CUSTOMER_ID, ACCOUNT_NUMBER, BALANCE, CREATED_AT)
VALUES (1, 1, 123456789123, 5000, DATE '2024-01-01');

INSERT INTO HOLDING (HOLDING_ID, FK_ACCOUNT_ID, FK_CUSTOMER_ID, FK_STOCK_ID, QUANTITY, AVARAGE_PRICE, LAST_UPDATED)
VALUES(1, 1, 1, 1, 3, 5000, DATE '2025-01-14');

INSERT INTO SECURITIES_ORDERS (ORDER_ID, ORDERT_TYPE, QUANTITY, PRICE, ORDER_STATUS, ORDER_DATE, FK_STOCK_ID, FK_ACCOUNT_ID, FK_CUSTOMER_ID)
VALUES(1, '국내', 3, 15000, '완료', DATE '2025-01-10', 1, 1, 1);

COMMIT;