-- 실습 과제 8
-- 지점 이름이 'Location 1'에 해당하는 지점에서 대출을 받은 고객의 이름 출력
SELECT NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM LOANS
    WHERE BRANCH_ID IN (
        SELECT BRANCH_ID
        FROM BRANCHES
        WHERE LOCATION = 'Location 1'));
        
SELECT NAME
FROM CUSTOMERS C, (
    SELECT CUSTOMER_ID
    FROM LOANS
    WHERE BRANCH_ID IN (
        SELECT BRANCH_ID
        FROM BRANCHES
        WHERE LOCATION = 'Location 1')) L
WHERE C.CUSTOMER_ID = L.CUSTOMER_ID;


-- 특정 고객(CUSTOMER_ID=100)이 소유한 모든 계좌에서 발생한 거래 출력
SELECT A.ACCOUNT_ID, T.TRANSACTION_ID
FROM TRANSACTIONS T, (
    SELECT ACCOUNT_ID
    FROM ACCOUNTS
    WHERE CUSTOMER_ID = 100) A
WHERE T.ACCOUNT_ID = A.ACCOUNT_ID;

SELECT ACCOUNT_ID, TRANSACTION_ID
FROM TRANSACTIONS
WHERE ACCOUNT_ID IN (
    SELECT ACCOUNT_ID
    FROM ACCOUNTS
    WHERE CUSTOMER_ID = 100);

-- 각 고객이 보유한 계좌 중 가장 높은 잔액을 가진 계좌를 조회
SELECT CUSTOMER_ID, ACCOUNT_ID, BALANCE
FROM ACCOUNTS A1
WHERE BALANCE = (
    SELECT MAX(BALANCE)
    FROM ACCOUNTS A2
    WHERE A1.CUSTOMER_ID = A2.CUSTOMER_ID);