-- 1
SELECT E.EMPLOYEE_ID EMPLOYEE_ID,
    NVL(J.JOB_ID, 'No Change') AS JOB_HISTORY
FROM EMPLOYEES E
LEFT OUTER JOIN JOB_HISTORY J
ON J.EMPLOYEE_ID = E.EMPLOYEE_ID;

-- 2
SELECT E.NAME EMPLOYEE, NVL(E.SALARY, 0) SALARY, D.DEPARTMENT_NAME DEPARTMENT
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.NAME LIKE '%Employee 1%'
ORDER BY LENGTH(DEPARTMENT), DEPARTMENT;

-- 3
SELECT T.TRANSACTION_ID TRANSACTION_ID,
    A.ACCOUNT_ID ACCOUNT,
    TO_CHAR(T.TRANSACTION_DATE,'YYYY-MM-DD HH24:MM:SS') TRANSACTION_DATE,
    C.CUSTOMER_ID CUSTOMER_ID,
    C.NAME CUSTOMER
FROM TRANSACTIONS T
INNER JOIN ACCOUNTS A
    ON T.ACCOUNT_ID = A.ACCOUNT_ID
INNER JOIN CUSTOMERS C
    ON A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE MONTHS_BETWEEN(SYSDATE, T.TRANSACTION_DATE) <= 6;

SELECT T.TRANSACTION_ID TRANSACTION_ID,
    A.ACCOUNT_ID ACCOUNT,
    TO_CHAR(T.TRANSACTION_DATE,'YYYY-MM-DD HH24:MM:SS') TRANSACTION_DATE,
    C.CUSTOMER_ID CUSTOMER_ID,
    C.NAME CUSTOMER
FROM TRANSACTIONS T, ACCOUNTS A, CUSTOMERS C
WHERE T.ACCOUNT_ID = A.ACCOUNT_ID
    AND A.CUSTOMER_ID = C.CUSTOMER_ID
    AND MONTHS_BETWEEN(SYSDATE, T.TRANSACTION_DATE) <= 6;

-- 4
SELECT E.JOB_ID JOB_ID, COUNT(*) TOTAL_EMPLOYEE
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND D.DEPARTMENT_NAME IN ('Department 3', 'Department 4', 'Department 5', 'Department 6')
GROUP BY E.JOB_ID;

-- 5
SELECT ACCOUNT_TYPE, TRUNC(AVG(BALANCE), 2) BALANCE
FROM ACCOUNTS
GROUP BY ACCOUNT_TYPE
ORDER BY BALANCE DESC;

-- 6
SELECT A.ACCOUNT_ID ACCOUNT_ID, COUNT(T.TRANSACTION_ID) CNT
FROM ACCOUNTS A
LEFT OUTER JOIN TRANSACTIONS T
    ON A.ACCOUNT_ID = T.ACCOUNT_ID
GROUP BY A.ACCOUNT_ID
ORDER BY CNT;

-- 7
SELECT CUSTOMER, TOTAL_TRANSACTION FROM (
    SELECT C.NAME CUSTOMER,
        SUM(T.AMOUNT) TOTAL_TRANSACTION
    FROM CUSTOMERS C, TRANSACTIONS T, ACCOUNTS A
    WHERE T.ACCOUNT_ID = A.ACCOUNT_ID
        AND A.CUSTOMER_ID = C.CUSTOMER_ID
        AND T.TRANSACTION_DATE BETWEEN TO_DATE('2024-01-01', 'YYYY-MM-DD')
            AND TO_DATE('2025-12-31', 'YYYY-MM-DD')
    GROUP BY C.NAME
    ORDER BY TOTAL_TRANSACTION DESC
)
WHERE ROWNUM <= 10;

-- 8
SELECT E.NAME EMPLOYEE, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY IS NULL;

-- 9
SELECT CUSTOMER, MAX_AMOUNT FROM (
    SELECT C.CUSTOMER_ID CUSTOMER_ID,
        C.NAME CUSTOMER,
        MAX(L.AMOUNT) MAX_AMOUNT
    FROM CUSTOMERS C, LOANS L
    WHERE C.CUSTOMER_ID = L.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID, C.NAME
    ORDER BY MAX_AMOUNT DESC
)
WHERE ROWNUM <= 15;

-- 10
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) CNT
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND E.SALARY BETWEEN 7000 AND 15000
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID) >= 5
ORDER BY CNT DESC;