-- 실습 과제 13

-- 1. 지점별 승인된 대출의 총 금액을 계산
-- 해당 금액이 전체 지점에서 승인된 대출금액의 평균보다 낮은 지점
-- 출력 컬럼 : 지점명, 승인된 대출의 총 금액, 전체 지점에서 승인된 대출 금액의 평균
-- 평균값은 반올림하여 소수점 아래 둘째자리까지 표현

SELECT * FROM (

    SELECT (SELECT NAME FROM BRANCHES WHERE BRANCH_ID = L.BRANCH_ID) BRANCH_NAME,
        SUM(AMOUNT) TOTAL_AMOUNT,
        ROUND(AVG(SUM(AMOUNT)) OVER (), 2) AVG_TOTAL_AMOUNT
    FROM LOANS L
    WHERE STATUS = 'APPROVED'
    GROUP BY BRANCH_ID
    
)
WHERE TOTAL_AMOUNT < AVG_TOTAL_AMOUNT
ORDER BY LENGTH(BRANCH_NAME), BRANCH_NAME;


SELECT (SELECT NAME FROM BRANCHES WHERE BRANCH_ID = L.BRANCH_ID) BRANCH_NAME,
    SUM(L.AMOUNT) TOTAL_AMOUNT,
    (SELECT ROUND(AVG(SUM(AMOUNT)), 2)
    FROM LOANS
    WHERE STATUS = 'APPROVED'
    GROUP BY BRANCH_ID) AVG_TOTAL_AMOUNT
FROM LOANS L
WHERE STATUS = 'APPROVED'
GROUP BY BRANCH_ID
HAVING SUM(L.AMOUNT) < (SELECT AVG(SUM(AMOUNT))
                        FROM LOANS
                        WHERE STATUS = 'APPROVED'
                        GROUP BY BRANCH_ID)
ORDER BY LENGTH(BRANCH_NAME), BRANCH_NAME;


SELECT DISTINCT
    (SELECT B.NAME FROM BRANCHES B WHERE B.BRANCH_ID = T.BRANCH_ID) AS BRANCH_NAME,
    T.BRANCH_SUM,
    ROUND((T.ALL_AVG),2) AS ALL_AVG
FROM (
    SELECT BRANCH_ID,
        SUM(AMOUNT) OVER(PARTITION BY BRANCH_ID) AS BRANCH_SUM,
        AVG(AMOUNT) OVER() AS ALL_AVG
    FROM LOANS
    WHERE STATUS = 'APPROVED'
    ) T
WHERE T.BRANCH_SUM < T.ALL_AVG;

-- 2. 모든 직원의 사번과 이름, 상사의 이름, 상사가 속한 부서 이름 출력
-- 상사가 없는 직원은 'NO MANAGER', 상사가 속한 부서가 없으면 'NO DEPARTMENT'

SELECT E.EMPLOYEE_ID,
    E.NAME,
    NVL((SELECT NAME
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID = E.MANAGER_ID), 'NO MANAGER') MANAGER_NAME,
    NVL((SELECT DEPARTMENT_NAME 
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = (
            SELECT DEPARTMENT_ID 
            FROM EMPLOYEES 
            WHERE EMPLOYEE_ID = E.MANAGER_ID)), 'NO DEPARTMENT') MANAGER_DEPT
FROM EMPLOYEES E
START WITH E.MANAGER_ID IS NULL
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID;

SELECT EMPLOYEE_ID,
    NAME,
    NVL(MANAGER_NAME, 'NO MANAGER') MANAGER_NAME,
    NVL((SELECT DEPARTMENT_NAME 
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = T.MANAGER_DEPT_ID), 'NO DEPARTMENT') MANAGER_DEPT
FROM (SELECT EMPLOYEE_ID,
        NAME,
        MANAGER_ID,
        (SELECT NAME
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID = E.MANAGER_ID) MANAGER_NAME,
        (SELECT DEPARTMENT_ID 
        FROM EMPLOYEES 
        WHERE EMPLOYEE_ID = E.MANAGER_ID) MANAGER_DEPT_ID
        FROM EMPLOYEES E) T
START WITH MANAGER_ID IS NULL
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

SELECT E1.EMPLOYEE_ID,
    E1.NAME,
    NVL(E2.NAME, 'NO MANAGER') MANAGER_NAME,
    NVL((SELECT DEPARTMENT_NAME 
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = E2.DEPARTMENT_ID), 'NO DEPARTMENT') MANAGER_DEPT
FROM EMPLOYEES E1
LEFT OUTER JOIN EMPLOYEES E2
 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
ORDER BY EMPLOYEE_ID;


-- 3. 각 직원의 급여와 그 급여가 전체 직원 급여에서 차지하는 백분율 계산
-- 출력 컬럼 : 사번, 이름, 급여, 백분율
-- 백분율은 소수점 둘째자리까지 반올림
-- 급여 없는 직원들 제외, 백분율 내림차순 정렬

SELECT EMPLOYEE_ID,
    NAME,
    SALARY,
    ROUND((SALARY / (SELECT SUM(SALARY) FROM EMPLOYEES))*100,2) PERCENT
FROM EMPLOYEES
WHERE SALARY IS NOT NULL
ORDER BY SALARY DESC;

SELECT EMPLOYEE_ID,
        NAME,
        SALARY,
        ROUND(PERCENT, 2) PERCENT
FROM (
    SELECT EMPLOYEE_ID,
        NAME,
        SALARY,
        (SALARY / (SELECT SUM(SALARY) FROM EMPLOYEES) * 100) PERCENT
    FROM EMPLOYEES
    WHERE SALARY IS NOT NULL
    ORDER BY PERCENT DESC
);

-- 4. 각 계좌의 최고 거래 금액이 높은 순으로 상위 5위까지의 계좌 출력
-- 동일 순위 존재할 경우, 각각의 순위를 모두 출력
-- 출력 컬럼 : 계좌 ID, 최고 거래 금액
SELECT *
FROM (
    SELECT T.*, DENSE_RANK() OVER(ORDER BY AMOUNT DESC) RANK
    FROM (
        SELECT ACCOUNT_ID ACCONT_ID,
            MAX(AMOUNT) AMOUNT
        FROM TRANSACTIONS
        GROUP BY ACCOUNT_ID
    ) T
)
WHERE RANK <= 5;

-- 확인용 쿼리
SELECT *
FROM (
    SELECT T.*, DENSE_RANK() OVER(ORDER BY AMOUNT DESC) RANK
    FROM (
        SELECT ACCOUNT_ID ACCONT_ID,
            MAX(AMOUNT) OVER(PARTITION BY ACCOUNT_ID) AMOUNT
        FROM TRANSACTIONS
    ) T
)
WHERE RANK <= 5;

SELECT ACCOUNT_ID, MAX_AMOUNT
FROM (
    SELECT ACCOUNT_ID ACCOUNT_ID,
        MAX(AMOUNT) MAX_AMOUNT,
        DENSE_RANK() OVER(ORDER BY MAX(AMOUNT) DESC) RANK
    FROM TRANSACTIONS
    GROUP BY ACCOUNT_ID
)
WHERE RANK <= 5;

-- 5. 각 부서에서 급여가 가장 높은 직원의 급여와 가장 낮은 직원의 급여 차이 계산
-- 부서ID로 오름차순 정렬
SELECT DISTINCT DEPARTMENT_ID,
    MAX(SALARY) OVER(PARTITION BY DEPARTMENT_ID) - MIN(SALARY) OVER(PARTITION BY DEPARTMENT_ID) DIFF_SALARY_MIN_MAX
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
ORDER BY DEPARTMENT_ID;

SELECT DISTINCT DEPARTMENT_ID,
    MAX(SALARY) - MIN(SALARY) DIFF_SALARY_MIN_MAX
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;


-- 6. 각 직원이 속한 부서별 평균 급여와 자신의 급여를 비교하여 급여의 차이를 계산
-- 자신의 급여가 높으면 양수, 낮으면 음수
-- 출력 컬럼 : 사번, 이름, 급여, 부서 평균 급여, 급여 차이
-- 부서 평균 급여와 급여 차이는 반올림하여 정수로 표현

SELECT EMPLOYEE_ID,
    NAME,
    SALARY,
    ROUND(AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID)) AVG_DEPT_SALARY,
    ROUND(SALARY - AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID)) DIFF_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,
    NAME,
    SALARY,
    ROUND(AVG_DEPT_SALARY) AVG_DEPT_SALARY,
    ROUND(SALARY - AVG_DEPT_SALARY) DIFF_SALARY
FROM (
    SELECT EMPLOYEE_ID,
        NAME,
        SALARY,
        AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID) AVG_DEPT_SALARY
    FROM EMPLOYEES
);

SELECT E.*, ROUND(SALARY - AVG_DEPT_SALARY) DIFF_SALARY
FROM (
    SELECT EMPLOYEE_ID,
        NAME,
        SALARY,
        ROUND(AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID)) AVG_DEPT_SALARY
    FROM EMPLOYEES
) E;

-- 7. 이름이 Employee 241인 사원의 모든 상사들을 출력

SELECT MAX(LTRIM(SYS_CONNECT_BY_PATH(NAME, ' > '), ' > ')) PATH
FROM EMPLOYEES
START WITH NAME = 'Employee 241'
CONNECT BY EMPLOYEE_ID = PRIOR MANAGER_ID;


-- 8. 사원 테이블에서 급여가 높은 상위 10명의 사원 정보를 출력
-- 급여 동일할 경우 사원 이름 순으로 정렬하여 순위 부여
SELECT * FROM (
SELECT NAME,
    SALARY,
    RANK() OVER(ORDER BY SALARY DESC NULLS LAST, NAME) RANK
FROM EMPLOYEES
)
WHERE RANK <= 10;

SELECT * FROM (
    SELECT NAME,
        SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC NULLS LAST, NAME
) E
WHERE ROWNUM <= 10;


-- 9. 입사 년도별 급여 합계를 출력하고 전체 급여 합계를 출력
-- 전체 급여 합계는 가장 아랫줄에 'ALL YEARS'로 표시

SELECT NVL(TO_CHAR(HIRE_DATE, 'YYYY'), 'ALL YEARS') YEAR, SUM(SALARY) TOTAL
FROM EMPLOYEES
WHERE HIRE_DATE IS NOT NULL
GROUP BY ROLLUP(TO_CHAR(HIRE_DATE, 'YYYY'))
ORDER BY YEAR;

-- 10. 부서별 급여 합계, 직무별 급여 합계, 전체 급여 합계 출력
-- 부서 정보가 NULL인 행 제외
-- 부서별, 직무별로 정렬
-- 출력 컬럼 : 부서명, 직무 ID, 급여 합계
SELECT NVL((SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = E.DEPARTMENT_ID), 'ALL DEPT') DEPT_NAME,
    NVL(JOB_ID, 'ALL JOB') JOB,
    SUM(SALARY) TOTAL_SALARY
FROM EMPLOYEES E
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(DEPARTMENT_ID, JOB_ID, ())
ORDER BY DEPARTMENT_ID, JOB_ID;

SELECT NVL(D.DEPARTMENT_NAME, 'ALL DEPT') DEPT_NAME,
    NVL(E.JOB_ID, 'ALL JOB') JOB,
    SUM(E.SALARY) TOTAL_SALARY
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY GROUPING SETS(D.DEPARTMENT_NAME, E.JOB_ID, ())
ORDER BY D.DEPARTMENT_NAME, E.JOB_ID;

-- 11. 각 직원의 급여와 해당 직원의 부서에서 그 직원의 급여보다 100 적은 급여부터 100 큰 급여까지 해당하는 급여의 합계
-- 출력 컬럼 : 부서 ID, 사원이름, 급여, 계산한 급여
SELECT DEPARTMENT_ID,
    NAME AS EMPLOYEE_NAME,
    SALARY,
    SUM(SALARY) OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY
                    RANGE BETWEEN 100 PRECEDING AND 100 FOLLOWING) SUM_OF_IN_RANGE
FROM EMPLOYEES;


-- 12. 각 직무별 평균 급여와 각 직원의 급여를 비교하여 "직무 평균 이상" 또는 "직무 평균 이하" 여부를 표시
-- 전체 평균 급여와의 비교 결과도 "전체 평균 이상" 또는 "전체 평균 이하"로 함께 표시
-- 출력 컬럼 : 사번, 급여, 직무 평균 급여 비교, 전체 평균 비교
SELECT EMPLOYEE_ID,
    SALARY,
    CASE
    WHEN AVG(SALARY) OVER() <= SALARY
        THEN '전체 평균 이상'
    ELSE'전체 평균 이하'
    END COMP_ALL,
    CASE
    WHEN AVG(SALARY) OVER(PARTITION BY JOB_ID) <= SALARY
        THEN '직무 평균 이상'
    ELSE '직무 평균 이하'
    END COMP_JOB
FROM EMPLOYEES
WHERE SALARY IS NOT NULL
ORDER BY EMPLOYEE_ID;