-- 실습 과제
-- 1. 각 지점의 이름과 대출 신청 고객 정보 출력(대출 신청 없는 지점 포함)
-- LEFT OUTER
SELECT B.NAME AS BRANCH_NAME,
    C.NAME AS CUSTOMER_NAME,
    L.AMOUNT AS LOAN_AMOUNT
FROM BRANCHES B
LEFT OUTER JOIN LOANS L
    ON B.BRANCH_ID = L.BRANCH_ID
LEFT OUTER JOIN CUSTOMERS C
    ON L.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY BRANCH_NAME, CUSTOMER_NAME NULLS FIRST;

-- RIGHT OUTER
SELECT B.NAME AS BRANCH_NAME,
    C.NAME AS CUSTOMER_NAME,
    L.AMOUNT AS LOAN_AMOUNT
FROM CUSTOMERS C
RIGHT OUTER JOIN LOANS L
    ON C.CUSTOMER_ID = L.CUSTOMER_ID
RIGHT OUTER JOIN BRANCHES B
    ON L.BRANCH_ID = B.BRANCH_ID
ORDER BY BRANCH_NAME, CUSTOMER_NAME NULLS FIRST;

-- WHERE(CUSTOMERS를 INNER JOIN한 것과 같음)
SELECT B.NAME AS BRANCH_NAME,
    C.NAME AS CUSTOMER_NAME,
    L.AMOUNT AS LOAN_AMOUNT
FROM BRANCHES B
LEFT OUTER JOIN LOANS L
    ON B.BRANCH_ID = L.BRANCH_ID,
CUSTOMERS C
WHERE L.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY BRANCH_NAME, CUSTOMER_NAME NULLS FIRST;

-- 2. 잔액이 50,000 이상인 계좌를 가진 고객의 이름과 이메일
-- INNER JOIN
SELECT C.NAME AS CUSTOMER_NAME,
    C.EMAIL AS CUSTOMER_EMAIL
FROM CUSTOMERS C
INNER JOIN ACCOUNTS A
    ON A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE A.BALANCE >= 50000;

-- WHERE
SELECT C.NAME AS CUSTOMER_NAME,
    C.EMAIL AS CUSTOMER_EMAIL
FROM CUSTOMERS C
WHERE C.CUSTOMER_ID IN (SELECT A.CUSTOMER_ID FROM ACCOUNTS A WHERE A.BALANCE  >= 50000);

-- 3. 대출 상태가 PENDING인 대출을 신청한 고객 이름과 이메일
SELECT C.NAME AS CUSTOMER_NAME,
    L.AMOUNT AS LOAN_AMOUNT
FROM CUSTOMERS C
INNER JOIN LOANS L
    ON C.CUSTOMER_ID = L.CUSTOMER_ID
WHERE L.STATUS = 'PENDING';