--실습과제 6
SELECT STATUS,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    COUNT(*) AS LOAN_COUNT
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY STATUS;

SELECT TO_CHAR(TRANSACTION_DATE, 'YYYY-MM') AS MONTH,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY TO_CHAR(TRANSACTION_DATE, 'YYYY-MM')
HAVING SUM(AMOUNT) > 10000
ORDER BY MONTH ASC;

SELECT BRANCH_ID,
    AVG(AMOUNT) AS AVG_AMOUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY BRANCH_ID
ORDER BY BRANCH_ID ASC;
