-- 실습 과제 12
-- 사원 테이블에서 부서별로 급여의 합계를 계산하고 전체 합계를 함께 출력하시오.
-- 단, 부서 데이터가 NULL인 사원은 제외
SELECT CASE
    WHEN GROUPING(E.DEPARTMENT_ID) = 0 THEN (
        SELECT DEPARTMENT_NAME
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = E.DEPARTMENT_ID)
    WHEN GROUPING(E.DEPARTMENT_ID) = 1 THEN '전체 합계'
    END DEPT_NAME,
    SUM(E.SALARY) SUM_SALARY
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(E.DEPARTMENT_ID)
ORDER BY LENGTH(DEPARTMENT_ID), DEPARTMENT_ID;

-- 같은 날짜에 입사한 사원이 2명 이상인 날짜와 입사한 사원 수, 마지막 행은 총 직원수를 함께 출력하시오.
SELECT CASE
    WHEN GROUPING(TO_CHAR(HIRE_DATE,'YYYY-MM-DD')) = 0 THEN TO_CHAR(HIRE_DATE,'YYYY-MM-DD')
    WHEN GROUPING(TO_CHAR(HIRE_DATE,'YYYY-MM-DD')) = 1 THEN '총 직원수'
    END HIRE_DATE,
    COUNT(*) CNT_EMPLOYEES
FROM EMPLOYEES E
GROUP BY ROLLUP(TO_CHAR(HIRE_DATE,'YYYY-MM-DD'))
HAVING COUNT(*) >= 2
ORDER BY HIRE_DATE;

-- 각 지점별 대출 금액 합계와 모든 지점의 총 합계를 출력하시오.
-- 출력 컬럼은 지점명, 대출 금액 합계이며 지점 총합계는 'All Branch'로 출력
-- 지점명으로 정렬하되 총합계는 맨 아랫줄에 나타내시오.
SELECT NVL((SELECT NAME FROM BRANCHES WHERE BRANCH_ID = L.BRANCH_ID), 'All Branch') BRANCH_NAME,
    SUM(AMOUNT) TOTAL_LOANS
FROM LOANS L
WHERE STATUS = 'APPROVED'
GROUP BY ROLLUP(BRANCH_ID)
ORDER BY LENGTH(BRANCH_ID), BRANCH_NAME;