--실습과제 5
SELECT NAME, EMAIL
FROM CUSTOMERS
ORDER BY NAME ASC, EMAIL DESC;

SELECT BALANCE, ACCOUNT_ID
FROM ACCOUNTS
ORDER BY BALANCE DESC, ACCOUNT_ID ASC;

SELECT TRANSACTION_TYPE, AMOUNT
FROM TRANSACTIONS
ORDER BY TRANSACTION_TYPE ASC, AMOUNT DESC;

SELECT STATUS, AMOUNT
FROM LOANS
ORDER BY STATUS ASC, AMOUNT DESC;